# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 01:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import timeline.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('link_form', models.BooleanField()),
                ('text_form', models.BooleanField()),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('teacher_type', models.CharField(choices=[('T', 'Teacher'), ('M', 'Master')], default='T', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TimelineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified Date Time')),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('title_link', models.URLField(max_length=500)),
                ('content', models.TextField(blank=True, null=True)),
                ('is_original', models.BooleanField()),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to=timeline.models.text_form_file_name)),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_item_creator', to=settings.AUTH_USER_MODEL)),
                ('item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeline.ItemCategory')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeline.Language')),
                ('likes', models.ManyToManyField(related_name='like_users', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeline.Teacher')),
                ('topics', models.ManyToManyField(related_name='timelineitems', to='timeline.ItemTopic')),
                ('users', models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimelineItemComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified Date Time')),
                ('comment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='timeline.TimelineItem')),
            ],
        ),
        migrations.CreateModel(
            name='UserLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_userlanguages', to='timeline.Language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_userlanguages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='language',
            name='users',
            field=models.ManyToManyField(related_name='languages', through='timeline.UserLanguage', to=settings.AUTH_USER_MODEL),
        ),
    ]
