# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 22:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('link_form', models.BooleanField()),
                ('text_form', models.BooleanField()),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('teacher_type', models.CharField(choices=[('T', 'Teacher'), ('M', 'Master')], default='T', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TimelineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_likes', models.IntegerField(default=0)),
                ('total_reblogs', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified Date Time')),
                ('title', models.CharField(blank=True, db_index=True, default='', max_length=500)),
                ('title_link', models.URLField(max_length=500)),
                ('content', models.TextField()),
                ('is_original', models.BooleanField()),
                ('created_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_item_creator', to=settings.AUTH_USER_MODEL)),
                ('item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeline.ItemCategory')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeline.Language')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeline.Teacher')),
                ('topics', models.ManyToManyField(to='timeline.ItemTopic')),
            ],
        ),
        migrations.CreateModel(
            name='TimelineItemComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified Date Time')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeline.TimelineItem')),
            ],
        ),
        migrations.CreateModel(
            name='UserLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_userlanguages', to='timeline.Language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_userlanguages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserTimelineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_timelineitems', to='timeline.TimelineItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_timelineitems', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='timelineitem',
            name='users',
            field=models.ManyToManyField(through='timeline.UserTimelineItem', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='language',
            name='users',
            field=models.ManyToManyField(through='timeline.UserLanguage', to=settings.AUTH_USER_MODEL),
        ),
    ]
