# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 19:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineitem',
            name='likes',
            field=models.ManyToManyField(related_name='like_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
