# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_auto_20170304_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineitem',
            name='file_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
