# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0004_timelineitem_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineitem',
            name='file_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
