# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 11:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0006_auto_20170305_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineitem',
            name='users',
            field=models.ManyToManyField(related_name='user_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
