# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0009_auto_20170328_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='lang_code',
            field=models.CharField(default='en', max_length=10),
            preserve_default=False,
        ),
    ]
