# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 16:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0012_auto_20170424_0205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemcategory',
            old_name='name_zh',
            new_name='name_zh_hans',
        ),
    ]
