# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-14 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0013_auto_20170426_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=225, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='itemtopic',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=225, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='timelineitem',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=225, null=True, unique=True),
        ),
    ]
