# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-14 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0014_auto_20170514_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='1', max_length=225, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemtopic',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='1', max_length=225, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timelineitem',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='1', max_length=225, unique=True),
            preserve_default=False,
        ),
    ]
