# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 14:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(blank=True, default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_notified', models.BooleanField(default=False, verbose_name='Is notified ?')),
                ('is_show', models.BooleanField(default=True, verbose_name='Is show ?')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_follower', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
