# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 12:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import easy_thumbnails.fields
import userena.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mugshot', easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text='A personal image displayed in your profile.', upload_to=userena.models.upload_to_mugshot, verbose_name='mugshot')),
                ('privacy', models.CharField(choices=[('open', 'Open'), ('registered', 'Registered'), ('closed', 'Closed')], default='registered', help_text='Designates who can view your profile.', max_length=15, verbose_name='privacy')),
                ('state', models.CharField(max_length=50)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('address1', models.CharField(blank=True, max_length=255)),
                ('address2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('zipcode', models.CharField(blank=True, max_length=50)),
                ('type', models.CharField(blank=True, choices=[('TEA', 'Buddhist Teacher'), ('BUD', 'Regular Buddhist'), ('Other', 'Other')], max_length=10)),
                ('paypal_email', models.EmailField(blank=True, max_length=100)),
                ('pay_url', models.URLField(blank=True, max_length=255)),
                ('donate_url', models.URLField(blank=True, max_length=255)),
                ('facebook', models.URLField(blank=True, max_length=255)),
                ('website', models.URLField(blank=True, max_length=255)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True)),
                ('payment_description', models.TextField(blank=True)),
                ('pickup_description', models.TextField(blank=True)),
                ('max_per_order', models.PositiveIntegerField(default=5)),
                ('local_pickup', models.BooleanField(default=False)),
                ('domestic_pay_shipping', models.BooleanField(default=False)),
                ('domestic_free_shipping', models.BooleanField(default=False)),
                ('international_free_shipping', models.BooleanField(default=False)),
                ('payinfo_for_donation', models.BooleanField(default=False)),
                ('donation', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('REG', 'Registerd'), ('ACT', 'Active'), ('DEA', 'Dead')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'permissions': (('view_profile', 'Can view profile'),),
            },
        ),
    ]
